name: job with variables
on: push
jobs:
 deploy-staging:
  runs-on: ubuntu-latest
  env:
   AWS_REGION: us-east-1
   CONTAINER_NAME: nice-app-service
  steps:
  - name: checkout the code
    uses: actions/checkout@v4
  - name: configure AWS credential
    uses: aws-actions/configure-aws-credentials@v4
    with:
     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
     aws-security-access-key: ${{ secrets.AWS_SECURITY_ACCESS_KEY }}
     aws-region: ${{ env.AWS_REGION }}
